/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SinaisVitaisRouteImport } from './routes/sinais-vitais'
import { Route as ResidentesRouteImport } from './routes/residentes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReceitasRouteImport } from './routes/receitas'
import { Route as PrimeirosSocorrosRouteImport } from './routes/primeiros-socorros'
import { Route as InsumosRouteImport } from './routes/insumos'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as HaldolRouteImport } from './routes/haldol'
import { Route as FichaSinaisVitaisRouteImport } from './routes/ficha-sinais-vitais'
import { Route as FarmacologiaRouteImport } from './routes/farmacologia'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as DispensacaoRouteImport } from './routes/dispensacao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgendamentosRouteImport } from './routes/agendamentos'
import { Route as AdministracaoRouteImport } from './routes/administracao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResidentesIdRouteImport } from './routes/residentes.$id'
import { Route as ReceitasTestarRouteImport } from './routes/receitas_.testar'
import { Route as ReceitasImportarRouteImport } from './routes/receitas_.importar'
import { Route as ReceitasArquivoRouteImport } from './routes/receitas_.arquivo'

const SinaisVitaisRoute = SinaisVitaisRouteImport.update({
  id: '/sinais-vitais',
  path: '/sinais-vitais',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentesRoute = ResidentesRouteImport.update({
  id: '/residentes',
  path: '/residentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasRoute = ReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeirosSocorrosRoute = PrimeirosSocorrosRouteImport.update({
  id: '/primeiros-socorros',
  path: '/primeiros-socorros',
  getParentRoute: () => rootRouteImport,
} as any)
const InsumosRoute = InsumosRouteImport.update({
  id: '/insumos',
  path: '/insumos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const HaldolRoute = HaldolRouteImport.update({
  id: '/haldol',
  path: '/haldol',
  getParentRoute: () => rootRouteImport,
} as any)
const FichaSinaisVitaisRoute = FichaSinaisVitaisRouteImport.update({
  id: '/ficha-sinais-vitais',
  path: '/ficha-sinais-vitais',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmacologiaRoute = FarmacologiaRouteImport.update({
  id: '/farmacologia',
  path: '/farmacologia',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const DispensacaoRoute = DispensacaoRouteImport.update({
  id: '/dispensacao',
  path: '/dispensacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentosRoute = AgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministracaoRoute = AdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentesIdRoute = ResidentesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResidentesRoute,
} as any)
const ReceitasTestarRoute = ReceitasTestarRouteImport.update({
  id: '/receitas_/testar',
  path: '/receitas/testar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasImportarRoute = ReceitasImportarRouteImport.update({
  id: '/receitas_/importar',
  path: '/receitas/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceitasArquivoRoute = ReceitasArquivoRouteImport.update({
  id: '/receitas_/arquivo',
  path: '/receitas/arquivo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/agendamentos': typeof AgendamentosRoute
  '/auth': typeof AuthRoute
  '/dispensacao': typeof DispensacaoRoute
  '/estoque': typeof EstoqueRoute
  '/farmacologia': typeof FarmacologiaRoute
  '/ficha-sinais-vitais': typeof FichaSinaisVitaisRoute
  '/haldol': typeof HaldolRoute
  '/indicadores': typeof IndicadoresRoute
  '/insumos': typeof InsumosRoute
  '/primeiros-socorros': typeof PrimeirosSocorrosRoute
  '/receitas': typeof ReceitasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/residentes': typeof ResidentesRouteWithChildren
  '/sinais-vitais': typeof SinaisVitaisRoute
  '/receitas/arquivo': typeof ReceitasArquivoRoute
  '/receitas/importar': typeof ReceitasImportarRoute
  '/receitas/testar': typeof ReceitasTestarRoute
  '/residentes/$id': typeof ResidentesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/agendamentos': typeof AgendamentosRoute
  '/auth': typeof AuthRoute
  '/dispensacao': typeof DispensacaoRoute
  '/estoque': typeof EstoqueRoute
  '/farmacologia': typeof FarmacologiaRoute
  '/ficha-sinais-vitais': typeof FichaSinaisVitaisRoute
  '/haldol': typeof HaldolRoute
  '/indicadores': typeof IndicadoresRoute
  '/insumos': typeof InsumosRoute
  '/primeiros-socorros': typeof PrimeirosSocorrosRoute
  '/receitas': typeof ReceitasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/residentes': typeof ResidentesRouteWithChildren
  '/sinais-vitais': typeof SinaisVitaisRoute
  '/receitas/arquivo': typeof ReceitasArquivoRoute
  '/receitas/importar': typeof ReceitasImportarRoute
  '/receitas/testar': typeof ReceitasTestarRoute
  '/residentes/$id': typeof ResidentesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administracao': typeof AdministracaoRoute
  '/agendamentos': typeof AgendamentosRoute
  '/auth': typeof AuthRoute
  '/dispensacao': typeof DispensacaoRoute
  '/estoque': typeof EstoqueRoute
  '/farmacologia': typeof FarmacologiaRoute
  '/ficha-sinais-vitais': typeof FichaSinaisVitaisRoute
  '/haldol': typeof HaldolRoute
  '/indicadores': typeof IndicadoresRoute
  '/insumos': typeof InsumosRoute
  '/primeiros-socorros': typeof PrimeirosSocorrosRoute
  '/receitas': typeof ReceitasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/residentes': typeof ResidentesRouteWithChildren
  '/sinais-vitais': typeof SinaisVitaisRoute
  '/receitas_/arquivo': typeof ReceitasArquivoRoute
  '/receitas_/importar': typeof ReceitasImportarRoute
  '/receitas_/testar': typeof ReceitasTestarRoute
  '/residentes/$id': typeof ResidentesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracao'
    | '/agendamentos'
    | '/auth'
    | '/dispensacao'
    | '/estoque'
    | '/farmacologia'
    | '/ficha-sinais-vitais'
    | '/haldol'
    | '/indicadores'
    | '/insumos'
    | '/primeiros-socorros'
    | '/receitas'
    | '/reset-password'
    | '/residentes'
    | '/sinais-vitais'
    | '/receitas/arquivo'
    | '/receitas/importar'
    | '/receitas/testar'
    | '/residentes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administracao'
    | '/agendamentos'
    | '/auth'
    | '/dispensacao'
    | '/estoque'
    | '/farmacologia'
    | '/ficha-sinais-vitais'
    | '/haldol'
    | '/indicadores'
    | '/insumos'
    | '/primeiros-socorros'
    | '/receitas'
    | '/reset-password'
    | '/residentes'
    | '/sinais-vitais'
    | '/receitas/arquivo'
    | '/receitas/importar'
    | '/receitas/testar'
    | '/residentes/$id'
  id:
    | '__root__'
    | '/'
    | '/administracao'
    | '/agendamentos'
    | '/auth'
    | '/dispensacao'
    | '/estoque'
    | '/farmacologia'
    | '/ficha-sinais-vitais'
    | '/haldol'
    | '/indicadores'
    | '/insumos'
    | '/primeiros-socorros'
    | '/receitas'
    | '/reset-password'
    | '/residentes'
    | '/sinais-vitais'
    | '/receitas_/arquivo'
    | '/receitas_/importar'
    | '/receitas_/testar'
    | '/residentes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministracaoRoute: typeof AdministracaoRoute
  AgendamentosRoute: typeof AgendamentosRoute
  AuthRoute: typeof AuthRoute
  DispensacaoRoute: typeof DispensacaoRoute
  EstoqueRoute: typeof EstoqueRoute
  FarmacologiaRoute: typeof FarmacologiaRoute
  FichaSinaisVitaisRoute: typeof FichaSinaisVitaisRoute
  HaldolRoute: typeof HaldolRoute
  IndicadoresRoute: typeof IndicadoresRoute
  InsumosRoute: typeof InsumosRoute
  PrimeirosSocorrosRoute: typeof PrimeirosSocorrosRoute
  ReceitasRoute: typeof ReceitasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResidentesRoute: typeof ResidentesRouteWithChildren
  SinaisVitaisRoute: typeof SinaisVitaisRoute
  ReceitasArquivoRoute: typeof ReceitasArquivoRoute
  ReceitasImportarRoute: typeof ReceitasImportarRoute
  ReceitasTestarRoute: typeof ReceitasTestarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sinais-vitais': {
      id: '/sinais-vitais'
      path: '/sinais-vitais'
      fullPath: '/sinais-vitais'
      preLoaderRoute: typeof SinaisVitaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residentes': {
      id: '/residentes'
      path: '/residentes'
      fullPath: '/residentes'
      preLoaderRoute: typeof ResidentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas': {
      id: '/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof ReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiros-socorros': {
      id: '/primeiros-socorros'
      path: '/primeiros-socorros'
      fullPath: '/primeiros-socorros'
      preLoaderRoute: typeof PrimeirosSocorrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insumos': {
      id: '/insumos'
      path: '/insumos'
      fullPath: '/insumos'
      preLoaderRoute: typeof InsumosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haldol': {
      id: '/haldol'
      path: '/haldol'
      fullPath: '/haldol'
      preLoaderRoute: typeof HaldolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ficha-sinais-vitais': {
      id: '/ficha-sinais-vitais'
      path: '/ficha-sinais-vitais'
      fullPath: '/ficha-sinais-vitais'
      preLoaderRoute: typeof FichaSinaisVitaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmacologia': {
      id: '/farmacologia'
      path: '/farmacologia'
      fullPath: '/farmacologia'
      preLoaderRoute: typeof FarmacologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispensacao': {
      id: '/dispensacao'
      path: '/dispensacao'
      fullPath: '/dispensacao'
      preLoaderRoute: typeof DispensacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamentos': {
      id: '/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AgendamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administracao': {
      id: '/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AdministracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residentes/$id': {
      id: '/residentes/$id'
      path: '/$id'
      fullPath: '/residentes/$id'
      preLoaderRoute: typeof ResidentesIdRouteImport
      parentRoute: typeof ResidentesRoute
    }
    '/receitas_/testar': {
      id: '/receitas_/testar'
      path: '/receitas/testar'
      fullPath: '/receitas/testar'
      preLoaderRoute: typeof ReceitasTestarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas_/importar': {
      id: '/receitas_/importar'
      path: '/receitas/importar'
      fullPath: '/receitas/importar'
      preLoaderRoute: typeof ReceitasImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receitas_/arquivo': {
      id: '/receitas_/arquivo'
      path: '/receitas/arquivo'
      fullPath: '/receitas/arquivo'
      preLoaderRoute: typeof ReceitasArquivoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResidentesRouteChildren {
  ResidentesIdRoute: typeof ResidentesIdRoute
}

const ResidentesRouteChildren: ResidentesRouteChildren = {
  ResidentesIdRoute: ResidentesIdRoute,
}

const ResidentesRouteWithChildren = ResidentesRoute._addFileChildren(
  ResidentesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministracaoRoute: AdministracaoRoute,
  AgendamentosRoute: AgendamentosRoute,
  AuthRoute: AuthRoute,
  DispensacaoRoute: DispensacaoRoute,
  EstoqueRoute: EstoqueRoute,
  FarmacologiaRoute: FarmacologiaRoute,
  FichaSinaisVitaisRoute: FichaSinaisVitaisRoute,
  HaldolRoute: HaldolRoute,
  IndicadoresRoute: IndicadoresRoute,
  InsumosRoute: InsumosRoute,
  PrimeirosSocorrosRoute: PrimeirosSocorrosRoute,
  ReceitasRoute: ReceitasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResidentesRoute: ResidentesRouteWithChildren,
  SinaisVitaisRoute: SinaisVitaisRoute,
  ReceitasArquivoRoute: ReceitasArquivoRoute,
  ReceitasImportarRoute: ReceitasImportarRoute,
  ReceitasTestarRoute: ReceitasTestarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
